#!/usr/bin/env node
/*
 * Derives each dossier's overview metrics from the COMPILED canonical
 * dataset (T-028 fáze G) instead of counting content/** pages — writes
 * data/dossiers/<slug>/stats.toml, which templates load via load_data().
 * Deterministic, no network access.
 *
 * Zdroj počtů: compiled model (data/dossiers/** JSON → compileDataset).
 * Do fáze H běží obsah i kanonická data souběžně, proto tenhle skript
 * dál KŘÍŽOVĚ OVĚŘUJE počty proti content/dossiers/<slug>/ — počet
 * claim řádků v přehledové tabulce (<a id="clm-##">) a [[extra.cases]]
 * bloků v _index.md musí sedět na kanonické počty. To není čtení dat
 * z front matter (data jdou z compiled modelu) — je to dvojitá pojistka
 * „oba toky musí souhlasit" (mise § fáze G), která zanikne až s fází H.
 *
 * Counts per dossier:
 *   claims_total    — kanonické claim záznamy dossieru
 *   cases_total     — kanonické case záznamy
 *   sources_total   — kanonické source záznamy
 *   gaps_total      — kanonické gap záznamy
 *   entities_total  — GLOBÁLNÍ entity, jejichž `dossiers` obsahuje slug
 *                     (entity nevlastní žádný dossier — filtr, ne výčet)
 *   relations_total — kanonické relation záznamy
 *
 * Entity dossiers (petr-macinka, filip-turek) vlastní žádné záznamy —
 * jejich počty jsou filtr záznamů kanonického dossieru podle `subjects`
 * (stejný mechanismus jako view modely fáze E a dnešní šablony). SELF-
 * canonical entity dossier (canonical_dossier == vlastní slug) vlastní
 * záznamy přímo a nefiltruje se.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { getDossierRecord } from "./lib/dossier-registry.mjs";
import { getCompiledModel, recordsOf } from "./lib/compiled-model.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const DOSSIERS_ROOT = join(ROOT, "content/dossiers");
const DATA_ROOT = join(ROOT, "data/dossiers");

function writeStats(slug, counts) {
  const OUT_DIR = join(DATA_ROOT, slug);
  const OUT_FILE = join(OUT_DIR, "stats.toml");
  const toml = `# Generated by scripts/dossier/generate-stats.mjs — do not hand-edit.
# Regenerated on every \`npm run build\`/\`npm run dev\` from this dossier's
# actual registries, so these numbers can't drift from what's really on
# the page.
claims_total = ${counts.claimsTotal}
cases_total = ${counts.casesTotal}
sources_total = ${counts.sourcesTotal}
gaps_total = ${counts.gapsTotal}
entities_total = ${counts.entitiesTotal}
relations_total = ${counts.relationsTotal}
`;
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, toml, "utf8");
  console.log(`[${slug}] Wrote ${OUT_FILE}: ${counts.claimsTotal} claims, ${counts.casesTotal} cases, ${counts.sourcesTotal} sources, ${counts.gapsTotal} gaps, ${counts.entitiesTotal} entities, ${counts.relationsTotal} relations.`);
}

const compiled = getCompiledModel(ROOT);

const entitiesTotalFor = (slug) =>
  compiled.entities.filter((w) => (w.record.dossiers ?? []).includes(slug)).length;

// Záznamy viditelné v dossieru: entity VIEW (canonical_dossier != slug)
// filtruje záznamy kanonického vlastníka podle subject taggingu; všechno
// ostatní vlastní své záznamy přímo.
function countsFor(slug, record) {
  const isView = record && record.dossierType === "entity" && record.canonicalDossier && record.canonicalDossier !== slug;
  const owner = isView ? record.canonicalDossier : slug;
  const visible = (registry) => {
    const rows = recordsOf(compiled, owner, registry);
    return isView ? rows.filter((w) => (w.record.subjects ?? []).includes(record.subject)) : rows;
  };
  return {
    claimsTotal: visible("claims").length,
    casesTotal: visible("cases").length,
    sourcesTotal: visible("sources").length,
    gapsTotal: visible("gaps").length,
    entitiesTotal: entitiesTotalFor(slug),
    relationsTotal: visible("relations").length,
  };
}

// Dvojitá pojistka do fáze H: kanonické počty musí sedět na to, co
// skutečně leží v content/ (přehledová tabulka + [[extra.cases]] bloky).
// Data se odtud NEČTOU — jen se porovnává počet.
function crossCheckAgainstContent(slug, counts) {
  const indexFile = join(DOSSIERS_ROOT, slug, "_index.md");
  if (!existsSync(indexFile)) {
    throw new Error(`generate-stats: [${slug}] kanonický dossier nemá content/dossiers/${slug}/_index.md — obsahová a kanonická vrstva se rozešly.`);
  }
  const dossierText = readFileSync(indexFile, "utf8");
  const tableClaimRows = [...dossierText.matchAll(/<a id="clm-\d+">/g)].length;
  const tableCaseBlocks = [...dossierText.matchAll(/^\[\[extra\.cases\]\]/gm)].length;

  if (counts.claimsTotal === 0) throw new Error(`generate-stats: [${slug}] found 0 canonical claim records.`);
  if (counts.sourcesTotal === 0) throw new Error(`generate-stats: [${slug}] found 0 canonical source records.`);
  if (counts.claimsTotal !== tableClaimRows) {
    throw new Error(
      `generate-stats: [${slug}] ${counts.claimsTotal} canonical claim record(s) but ${tableClaimRows} CLM row(s) in the overview table — they must match 1:1. Run scripts/dossier/migrate-claims-to-pages.mjs after editing the table (and re-run npm run data:migrate), or fix the drift manually.`,
    );
  }
  if (counts.casesTotal !== tableCaseBlocks) {
    throw new Error(
      `generate-stats: [${slug}] ${counts.casesTotal} canonical case record(s) but ${tableCaseBlocks} [[extra.cases]] entr(y/ies) in front matter — they must match 1:1. Run scripts/dossier/migrate-cases-to-pages.mjs after editing the array (and re-run npm run data:migrate), or fix the drift manually.`,
    );
  }
}

const dossierWrappers = compiled.records.filter((w) => w.registry === "dossier");
if (dossierWrappers.length === 0) {
  throw new Error("generate-stats: no dossiers found in the canonical dataset (data/dossiers/).");
}
for (const w of dossierWrappers) {
  const slug = w.dossier;
  const record = getDossierRecord(slug);
  const counts = countsFor(slug, record);
  if (!record || record.dossierType !== "entity") {
    crossCheckAgainstContent(slug, counts);
  }
  writeStats(slug, counts);
}
