#!/usr/bin/env node
/*
 * Derives dossier overview metrics from the registries themselves instead
 * of letting them be hand-typed (and drift) in content/dossier/_index.md
 * front matter. Writes data/dossier-stats.toml, which templates/dossier.html
 * loads via load_data(). Deterministic, no network access.
 *
 * Counts:
 *   claims_total  — <a id="clm-##"> anchors in the claims registry table
 *   cases_total   — [[extra.cases]] blocks in front matter (tracked cases)
 *   sources_total — content/dossier/zdroje/src-*.md pages
 *   gaps_total    — content/dossier/mezery/gap-*.md pages
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const DOSSIER_MD = join(ROOT, "content/dossier/_index.md");
const SRC_DIR = join(ROOT, "content/dossier/zdroje");
const GAP_DIR = join(ROOT, "content/dossier/mezery");
const OUT_FILE = join(ROOT, "data/dossier-stats.toml");

const dossierText = readFileSync(DOSSIER_MD, "utf8");

const claimsTotal = [...dossierText.matchAll(/<a id="clm-\d+">/g)].length;
const casesTotal = [...dossierText.matchAll(/^\[\[extra\.cases\]\]/gm)].length;

const sourcesTotal = readdirSync(SRC_DIR).filter(
  (f) => /^src-\d+\.md$/.test(f),
).length;
const gapsTotal = readdirSync(GAP_DIR).filter(
  (f) => /^gap-\d+\.md$/.test(f),
).length;

if (claimsTotal === 0) throw new Error("generate-stats: found 0 CLM anchors — table format may have changed.");
if (sourcesTotal === 0) throw new Error("generate-stats: found 0 source pages in content/dossier/zdroje.");

const toml = `# Generated by scripts/dossier/generate-stats.mjs — do not hand-edit.
# Regenerated on every \`npm run build\`/\`npm run dev\` from the actual
# claims/sources/gaps registries, so these numbers can't drift from what's
# really on the page.
claims_total = ${claimsTotal}
cases_total = ${casesTotal}
sources_total = ${sourcesTotal}
gaps_total = ${gapsTotal}
`;

writeFileSync(OUT_FILE, toml, "utf8");
console.log(`Wrote ${OUT_FILE}: ${claimsTotal} claims, ${casesTotal} cases, ${sourcesTotal} sources, ${gapsTotal} gaps.`);
