#!/usr/bin/env node
/*
 * Expand a company's registry neighbourhood into CONTEXT entity records.
 *
 * Given an IČO, this reads the ARES public-register (VR) branch and writes
 * one CANONICAL context entity record per legal person and per registered
 * natural person it finds — data/dossiers/_shared/entities/<id>.json
 * (T-028: the canonical JSON dataset is the only source of truth; the
 * content/entities/*.md pages are generated adapters, regenerated by
 * `npm run data:build`). It is the automated version of what an editor
 * otherwise does by hand after an ARES lookup.
 *
 * WHY THIS NEEDS NO AUTHORIZATION, AND WHERE THE LINE STILL IS
 * ------------------------------------------------------------
 * Everything written here is publicationRole = "context",
 * dossierEnabled = false, dossierStatus = "not_authorized", dossiers = []
 * — a record that a registry relation exists, carrying no claim, no source
 * citation and no dossier membership. That is the shape
 * build-government-roster.mjs already produces, and the authorization
 * validators (validate-authorization.mjs, canonical rule S6 in
 * scripts/data/validate-semantics.mjs) permit it explicitly: what they
 * forbid is a context entity acquiring dossierEnabled or
 * dossierStatus = "authorized".
 *
 * A DOSSIER about any of these people or companies — an investigation with
 * claims about them — still requires an explicit, dated authorization in
 * AGENTS.md written by a human through authorize-entity.mjs. This script
 * cannot and must not create one. Discovery is unblocked; publication of
 * findings is not.
 *
 * WHAT IS DELIBERATELY NOT COPIED FROM THE REGISTRY
 * -------------------------------------------------
 * The VR records contain dates of birth and residential addresses of named
 * private individuals. Those are dropped in stripPersonalData() — in code,
 * not by convention, so no later edit can reintroduce them by accident. A
 * registry being public does not make republishing someone's home address
 * proportionate; the constitution's public-interest test (§7) is per-record,
 * not per-source.
 *
 * WHAT ARES CAN AND CANNOT EVIDENCE HERE
 * --------------------------------------
 *   CAN: identity (IČO), registered name and its history, legal form, seat,
 *        registered statutory bodies with their terms, and — via the VR
 *        branch used here — registered shareholders of an s.r.o. with the
 *        recorded size of their share.
 *   CANNOT: beneficial owners (separate register), and shareholders of an
 *        a.s., which are generally not registered at all. An empty
 *        shareholder list means "not registered here", never "this company
 *        has no owners".
 *
 * NOTE: scripts/osint/ares-lookup.mjs states ARES cannot evidence
 * shareholders. That holds for the basic endpoint it uses, but not for the
 * VR branch used here — verified 2026-07-30 against IČO 28274318, which
 * returns `spolecnici` with `velikostPodilu`. That caveat needs correcting.
 *
 * Live network call, never part of `npm run build`.
 *
 * Usage:
 *   node scripts/osint/expand-entity.mjs --ico=28274318            # dry run
 *   node scripts/osint/expand-entity.mjs --ico=28274318 --write
 *   ... [--json]
 */
import { writeFileSync, readdirSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { slugify, findPossibleDuplicate } from "./lib/entity-dedupe.mjs";
import { validateRecordObject } from "../data/validate-shape.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const ENTITIES_DIR = join(ROOT, "data", "dossiers", "_shared", "entities");
const VR_ENDPOINT =
  "https://ares.gov.cz/ekonomicke-subjekty-v-be/rest/ekonomicke-subjekty-vr";

function parseArgs(argv) {
  const out = {};
  for (const a of argv) {
    const m = a.match(/^--([a-z-]+)(?:=(.*))?$/s);
    if (m) out[m[1]] = m[2] ?? true;
  }
  return out;
}

// --- fetch ----------------------------------------------------------------

async function fetchVr(ico) {
  const res = await fetch(`${VR_ENDPOINT}/${ico}`, {
    headers: { accept: "application/json" },
  });
  if (res.status === 404) {
    console.error(`expand-entity: IČO ${ico} not found in the public register.`);
    process.exit(1);
  }
  if (!res.ok) {
    console.error(`expand-entity: ARES returned ${res.status}.`);
    process.exit(1);
  }
  return res.json();
}

// --- extraction -----------------------------------------------------------

const current = (x) => !x?.datumVymazu;

/* Most VR scalars arrive as [{datumZapisu, hodnota}], including `ico`.
   Reading them raw yields "[object Object]" in output — caught by the first
   dry run against IČO 28274318. */
const value = (v) => {
  if (Array.isArray(v)) return value(v.find(current) ?? v[0]);
  if (v && typeof v === "object" && "hodnota" in v) return String(v.hodnota);
  return v == null ? null : String(v);
};

/* The single place personal data is dropped. Everything downstream sees only
   what this returns, so no later change can reintroduce a birth date or a
   home address into a generated record. */
function titleCase(name) {
  // The register stores personal names in caps ("PETR VENCÁLEK"); rendering
  // that as a record title would be wrong. Hyphenated surnames keep both
  // parts capitalised.
  return name
    .toLocaleLowerCase("cs")
    .replace(/(^|[\s-])(\p{L})/gu, (_, sep, ch) => sep + ch.toLocaleUpperCase("cs"));
}

function stripPersonalData(fo) {
  const bare = [fo.jmeno, fo.prijmeni].filter(Boolean).join(" ");
  return {
    // Academic titles are kept for display but excluded from the slug: the
    // register gained "Bc." for this very person in 2022, and an id that
    // moves when someone finishes a degree is not an id.
    name: [fo.titulPredJmenem, titleCase(bare)].filter(Boolean).join(" "),
    slugSource: bare,
    // datumNarozeni and adresa are intentionally NOT read.
  };
}

function personOrCompany(osoba) {
  if (osoba?.fyzickaOsoba) {
    return { kind: "person", ...stripPersonalData(osoba.fyzickaOsoba) };
  }
  const po = osoba?.pravnickaOsoba;
  if (po) return { kind: "company", name: value(po.obchodniJmeno), ico: value(po.ico) };
  return null;
}

function dedupe(list) {
  const seen = new Set();
  return list.filter((x) => {
    const key = `${x.kind}:${x.ico ?? x.name}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function extract(record) {
  const names = record.obchodniJmeno ?? [];
  const seat = (record.adresy ?? []).find(current)?.adresa?.textovaAdresa ?? null;

  const officers = [];
  for (const organ of record.statutarniOrgany ?? []) {
    for (const m of organ.clenoveOrganu ?? []) {
      if (!current(m)) continue;
      const who = personOrCompany(m);
      if (!who) continue;
      officers.push({ ...who, role: m.clenstvi?.funkce?.nazev ?? "člen orgánu" });
    }
  }

  const shareholders = [];
  for (const blok of record.spolecnici ?? []) {
    for (const s of blok.spolecnik ?? []) {
      if (!current(s)) continue;
      const who = personOrCompany(s.osoba);
      if (!who) continue;
      const podil = (s.podil ?? []).find(current)?.velikostPodilu;
      shareholders.push({ ...who, share: podil ? String(podil.hodnota) : null });
    }
  }

  return {
    ico: value(record.ico),
    name: value(names) ?? null,
    formerNames: names.filter((n) => !current(n)).map((n) => String(n.hodnota)),
    seat,
    officers: dedupe(officers),
    shareholders: dedupe(shareholders),
  };
}

// --- registry state -------------------------------------------------------

/* Canonical shared entities: one JSON record per file. `order` continues
   past the current maximum rather than renumbering anything that already
   exists (same invariant the old front-matter `weight` had). */
export function readEntitiesState(dir = ENTITIES_DIR) {
  const files = readdirSync(dir).filter((f) => f.endsWith(".json"));
  const existingIds = new Set(files.map((f) => f.replace(/\.json$/, "")));
  const entityTexts = new Map(
    files.map((f) => [f.replace(/\.json$/, ""), readFileSync(join(dir, f), "utf8")]),
  );
  let maxOrder = 0;
  for (const text of entityTexts.values()) {
    try {
      const order = JSON.parse(text)?.order;
      if (Number.isInteger(order) && order > maxOrder) maxOrder = order;
    } catch {
      /* nečitelný soubor odhalí data:validate; tady jen počítáme order */
    }
  }
  return { dir, existingIds, entityTexts, nextOrder: maxOrder + 1 };
}

// --- record rendering -----------------------------------------------------

const DISCLAIMER_COMPANY = `**Kontextová entita, ne předmět šetření.** Tahle stránka eviduje pouze to,
že subjekt existuje ve veřejném rejstříku a objevil se při rozšiřování
rejstříkového okolí. Nenese žádné tvrzení, nic nedokládá a neznamená
podezření ani hodnocení. Dossier o tomto subjektu by vyžadoval samostatné,
datované rozhodnutí zapsané v autorizačním logu.`;

const DISCLAIMER_PERSON = `**Kontextová entita, ne předmět šetření.** Tahle stránka eviduje jednu
zveřejněnou rejstříkovou vazbu a nic víc — žádný profil, žádné tvrzení,
žádné naznačené pochybení. Být zapsán ve statutárním orgánu nebo držet
podíl je běžný, veřejně evidovaný fakt. Dossier o této osobě by vyžadoval
samostatné, datované rozhodnutí zapsané v autorizačním logu.

Datum narození ani adresu bydliště tento web z rejstříku nepřebírá,
přestože je záznam obsahuje — pro evidenci vazby nejsou potřebné.`;

function entityRecord({ id, title, description, type, order, today, provenance, body, ico }) {
  const record = {
    $schema: "https://vomaste.cz/schemas/canonical/entity.schema.json",
    schemaVersion: 1,
    "@context": "https://vomaste.cz/context/v1.jsonld",
    "@id": `https://vomaste.cz/id/entities/${id}`,
    "@type": "vomaste:Entity",
    recordType: "entity",
    identifier: id,
    entityId: id,
    title,
    entityType: type,
    publicationRole: "context",
    dossierEnabled: false,
    dossierStatus: "not_authorized",
    coverageState: "referenced",
    dossiers: [],
    order,
    description,
    provenance: {
      discoveredAt: today,
      discoveredVia: [provenance],
      depth: 3,
    },
    content: [{ type: "markdown", value: body }],
  };
  if (ico) record.externalIds = { ares: String(ico) };
  return record;
}

export function renderCompany(c, order, { today, provenance }) {
  const former = c.formerNames?.length
    ? ` Dřívější zapsané názvy: ${c.formerNames.join(", ")}.`
    : "";
  const body =
    `Záznam z veřejného rejstříku (ARES), pořízený programově ${today}. IČO ${c.ico}.${
      c.seat ? ` Sídlo podle rejstříku: ${c.seat}.` : ""
    }${former}\n\n${DISCLAIMER_COMPANY}`;
  return entityRecord({
    id: c.id,
    title: c.name,
    description: `${c.name} (IČO ${c.ico}) — kontextový záznam rejstříkové vazby z ARES, ne dossier.`,
    type: "company",
    order,
    today,
    provenance,
    body,
    ico: c.ico,
  });
}

export function renderPerson(p, order, contextLine, { today, provenance }) {
  const body = `Záznam z veřejného rejstříku (ARES), pořízený programově ${today}:\n${contextLine}\n\n${DISCLAIMER_PERSON}`;
  return entityRecord({
    id: p.id,
    title: p.name,
    description: `${p.name} — kontextový záznam rejstříkové vazby z ARES, ne dossier.`,
    type: "person",
    order,
    today,
    provenance,
    body,
  });
}

// --- planning + execution -------------------------------------------------

export function planExpansion(data, { today, provenance }) {
  const planned = new Map();
  const plan = (id, kind, label, render, ident = {}) => {
    if (planned.has(id)) {
      planned.get(id).label += `; ${label.split(" — ").pop()}`;
      return;
    }
    // ident carries what findPossibleDuplicate needs (ico for companies,
    // slugSource for people). Without it the check silently never fires —
    // which is exactly what the first run did.
    planned.set(id, { id, kind, label, render, ...ident });
  };

  const selfId = (existingIds) =>
    existingIds.has(slugify(data.name)) ? `ico-${data.ico}` : slugify(data.name);

  return {
    finalize(existingIds) {
      plan(
        selfId(existingIds),
        "company",
        `${data.name} (IČO ${data.ico})`,
        (self, order) => renderCompany({ ...data, id: self.id }, order, { today, provenance }),
        { ico: data.ico, name: data.name },
      );

      for (const o of data.officers) {
        const id = o.ico ? `ico-${o.ico}` : slugify(o.slugSource ?? o.name);
        const label = o.kind === "person" ? o.name : `${o.name} (IČO ${o.ico})`;
        plan(id, o.kind, `${label} — ${o.role}`, (self, order) =>
          o.kind === "person"
            ? renderPerson(
                { ...o, id: self.id },
                order,
                `zapsán jako **${o.role}** společnosti ${data.name} (IČO ${data.ico}).`,
                { today, provenance },
              )
            : renderCompany({ ...o, id: self.id, formerNames: [], seat: null }, order, {
                today,
                provenance,
              }),
          { ico: o.ico, slugSource: o.slugSource, name: o.name },
        );
      }

      for (const s of data.shareholders) {
        const id = s.ico ? `ico-${s.ico}` : slugify(s.slugSource ?? s.name);
        const share = s.share ? ` (podíl ${s.share})` : "";
        const label = s.kind === "person" ? s.name : `${s.name} (IČO ${s.ico})`;
        plan(id, s.kind, `${label} — společník${share}`, (self, order) =>
          s.kind === "person"
            ? renderPerson(
                { ...s, id: self.id },
                order,
                `zapsán jako **společník**${share} společnosti ${data.name} (IČO ${data.ico}).`,
                { today, provenance },
              )
            : renderCompany({ ...s, id: self.id, formerNames: [], seat: null }, order, {
                today,
                provenance,
              }),
          { ico: s.ico, slugSource: s.slugSource, name: s.name },
        );
      }

      return planned;
    },
  };
}

/*
 * Applies the plan against a registry state (readEntitiesState result):
 * skips existing records (never overwrite), reports suspected duplicates
 * for human review (never auto-merges), and — with write=true — writes
 * canonical JSON records that MUST validate against
 * schemas/canonical/entity.schema.json (fail-closed: an invalid record is
 * a bug in this script, not something to put on disk).
 */
export function executePlan(planned, state, { write = false } = {}) {
  const created = [];
  const skipped = [];
  const suspected = [];
  let nextOrder = state.nextOrder;

  for (const p of planned.values()) {
    const dup = findPossibleDuplicate(p, state.entityTexts);
    if (dup) {
      suspected.push({ ...p, duplicateOf: dup.id, why: dup.why });
      continue;
    }
    if (state.existingIds.has(p.id)) {
      /* Never overwrite: an existing record may carry hand-written editorial
         context, dossier membership and claim links this script knows nothing
         about. Overwriting it would be data loss. A slug collision with a
         namesake also lands here — that is a signal for manual review, not a
         reason to add --force. */
      skipped.push(p);
      continue;
    }
    const order = nextOrder++;
    const record = p.render(p, order);
    const relPath = `data/dossiers/_shared/entities/${p.id}.json`;
    const shapeErrors = validateRecordObject(record, relPath);
    if (shapeErrors.length > 0) {
      throw new Error(
        `expand-entity: vygenerovaný záznam neprošel schématem — chyba skriptu, nezapisuji:\n  ${shapeErrors.join("\n  ")}`,
      );
    }
    if (write) {
      writeFileSync(join(state.dir, `${p.id}.json`), `${JSON.stringify(record, null, 2)}\n`, "utf8");
    }
    created.push({ ...p, record });
  }

  return { created, skipped, suspected };
}

// --- main -----------------------------------------------------------------

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const args = parseArgs(process.argv.slice(2));
  if (!args.ico) {
    console.error("expand-entity: usage: --ico=<8 digits> [--write] [--json]");
    process.exit(1);
  }
  if (!/^\d{8}$/.test(String(args.ico))) {
    console.error(`expand-entity: --ico must be 8 digits (got "${args.ico}").`);
    process.exit(1);
  }

  const today = new Date().toISOString().slice(0, 10);

  const payload = await fetchVr(String(args.ico));
  const record = payload?.zaznamy?.[0];
  if (!record) {
    console.error(`expand-entity: no VR record in the response for ${args.ico}.`);
    process.exit(1);
  }

  const data = extract(record);
  const provenance = `ares-expansion-${data.ico}-${today}`;
  const state = readEntitiesState();
  const planned = planExpansion(data, { today, provenance }).finalize(state.existingIds);
  const { created, skipped, suspected } = executePlan(planned, state, {
    write: Boolean(args.write),
  });

  const plain = (list) => list.map(({ id, kind, label }) => ({ id, kind, label }));

  if (args.json) {
    console.log(
      JSON.stringify(
        {
          ico: data.ico,
          provenance,
          wrote: Boolean(args.write),
          created: plain(created),
          skipped: plain(skipped),
          suspectedDuplicates: suspected.map(({ id, label, duplicateOf, why }) => ({ id, label, duplicateOf, why })),
        },
        null,
        2,
      ),
    );
  } else {
    console.log(`ARES expansion — ${data.name} (IČO ${data.ico}), ${today}`);
    console.log(args.write ? "mode: WRITE\n" : "mode: dry run (přidej --write)\n");
    console.log(
      `${created.length} kontextových entit${args.write ? " zapsáno" : " by vzniklo"} (kanonické JSON, data/dossiers/_shared/entities/):`,
    );
    for (const p of created) console.log(`  + ${p.id.padEnd(28)} ${p.label}`);
    if (skipped.length) {
      console.log(`\n${skipped.length} přeskočeno (záznam existuje, nikdy nepřepisuji):`);
      for (const p of skipped) console.log(`  = ${p.id.padEnd(28)} ${p.label}`);
    }
    if (suspected.length) {
      console.log(
        `\n${suspected.length} NEZALOŽENO — nejspíš už pro ně záznam existuje pod jiným id:`,
      );
      for (const p of suspected) {
        console.log(`  ? ${p.id.padEnd(28)} ${p.label}`);
        console.log(`    -> ${p.duplicateOf} (${p.why}) — ověř ručně, skript nespojuje`);
      }
    }
    console.log(
      '\nVše vytvořené je publicationRole = "context", dossiers = [], bez tvrzení.\n' +
        "Content adaptéry (/entities/…) přegeneruje `npm run data:build`.\n" +
        "Dossier o kterémkoli z nich vyžaduje samostatnou autorizaci\n" +
        "(scripts/dossier/authorize-entity.mjs). Datum narození ani adresu\n" +
        "bydliště skript z rejstříku nepřebírá.",
    );
  }
}
